[workspace]
members = ["tgrep-core", "tgrep-cli"]
exclude = ["vendor/ignore"]
resolver = "2"

[workspace.package]
version = "1.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/microsoft/tgrep"
authors = ["Shengyu Fu"]

[workspace.dependencies]
tgrep-core = { path = "tgrep-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
blake3 = "1"
rusqlite = { git = "https://github.com/rusqlite/rusqlite.git", rev = "2a71e35d94b2a02f7dd4a0c4cfd59c339370e747", features = ["bundled"] }
